$patch: delete
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata: # kpt-merge: istio-system/istio-ingressgateway
  name: istio-ingressgateway
  namespace: istio-system
---
$patch: delete
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata: # kpt-merge: istio-system/istiod
  name: istiod
  namespace: istio-system
