apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /knative-serving-namespaced-admin
  name: knative-serving-namespaced-admin
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /knative-serving-namespaced-edit
  name: knative-serving-namespaced-edit
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /knative-serving-namespaced-view
  name: knative-serving-namespaced-view
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
