apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: kfserving-system/kfserving-controller-manager
  name: kfserving-controller-manager
  namespace: kfserving-system
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
