apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: system/controller-manager
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      serviceAccountName: tensorboard-controller
