apiVersion: v1
kind: Service
metadata: # kpt-merge: system/webhook-service
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
