apiVersion: tensorboard.kubeflow.org/v1alpha1
kind: Tensorboard
metadata: # kpt-merge: kubeflow-quanlin/tensorboard-sample1
  name: tensorboard-sample1
  namespace: kubeflow-quanlin
spec:
  # Add fields here
  logspath: "gs://quanlinkubeflow1_tf_mnist_logs1/mnist_tutorial/"
