apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kubeflow-test-admin-manages-user # kpt-set: ${name}-admin-manages-user
spec:
  member: serviceAccount:kubeflow-test-admin@kfmlops.iam.gserviceaccount.com # kpt-set: serviceAccount:${name}-admin@${gcloud.core.project}.iam.gserviceaccount.com
  # "roles/serviceAccountAdmin" grants kf-admin service account permission to
  # manage workload identity binding policies for kf-user service account.
  role: roles/iam.serviceAccountAdmin
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kubeflow-test-user # kpt-set: ${name}-user
