apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: system/controller-manager
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: IMAGE_URL
        name: manager
