apiVersion: v1
kind: PersistentVolumeClaim
metadata: # kpt-merge: kubeflow/katib-mysql
  name: katib-mysql
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
