apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: kfserving-system/kfserving-controller-manager
  name: kfserving-controller-manager
  namespace: kfserving-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: kfserving/kfserving-controller:v0.6.1
        name: manager
