apiVersion: v1
kind: ConfigMap
metadata:
  name: kpt-setter-config
data:
  mgmt-ctxt: mgt-cluster # kpt-set: ${mgmt-ctxt}
  name: kubeflow-test # kpt-set: ${name}
  gcloud.core.project: kfmlops # kpt-set: ${gcloud.core.project}
  gcloud.project.projectNumber: 611731318788 # kpt-set: ${gcloud.project.projectNumber}
  location: asia-northeast1-a # kpt-set: ${location}
  gcloud.compute.zone: asia-northeast1-a # kpt-set: ${gcloud.compute.zone}
  gcloud.compute.region: asia-northeast1 # kpt-set: ${gcloud.compute.region}
  email: bharath.chakravarthi@gmail.com # kpt-set: ${email}
  asm-label: asm-1104-6 # kpt-set: ${asm-label}
  cloudsql-name: kubeflow-test-kfp # kpt-set: ${cloudsql-name}
  bucket-name: kfmlops-kfp # kpt-set: ${bucket-name}
  default-pipeline-root: gs://kfmlops-kfp/v2/artifacts # kpt-set: ${default-pipeline-root}
